name: Pull Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "The name of the docker image to pull."
        required: true
        type: string
        default: "pytorch/pytorch"
      docker_tag:
        description: "The tag of the docker image to pull."
        required: true
        type: string
        default: "latest"

env:
  # NOTE: Can't override DOCKER_HOST env as it breaks the docker CLI
  DKR_HOST: ${{ vars.DOCKER_HOST }}
  DKR_REPO: ${{ vars.DOCKER_REPO }}
  DKR_USER: ${{ secrets.DOCKER_USER }}
  DKR_PASS: ${{ secrets.DOCKER_PASS }}
  DKR_IMAGE: ${{ github.event.inputs.docker_image }}
  DKR_TAG: ${{ github.event.inputs.docker_tag }}


jobs:
  pull-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker repository
        uses: docker/login-action@v4
        with:
          ecr: false
          registry: ${{ env.DKR_HOST }}
          username: ${{ env.DKR_USER }}
          password: ${{ env.DKR_PASS }}

      - name: Pull the docker image
        run: |
          docker pull ${DKR_HOST}/${DKR_REPO}/${DKR_IMAGE}:${DKR_TAG}
